const image = (name) => `/assets/${name}.jpg`;
module.exports = () => ({
  horses: [
    {
      _id: "atlas",
      name: "Atlas",
      nameAr: "أطلس",
      slug: "atlas",
      breed: "Arabian",
      sex: "stallion",
      color: "Grey",
      dateOfBirth: "2019-04-12",
      status: "active",
      isFeatured: true,
      isStallion: true,
      availableForBreeding: true,
      description:
        "A graceful presence with an expressive eye and a generous spirit. Atlas represents the beauty and character at the heart of our vision.",
      descriptionAr:
        "حضور أنيق ونظرة معبرة وروح كريمة. يجسد أطلس الجمال والأصالة.",
      coverImage: { url: image("atlas") },
      pedigree: {
        sire: { name: "Amir" },
        dam: { name: "Nour" },
        paternalGrandsire: { name: "Sultan" },
        paternalGranddam: { name: "Layla" },
        maternalGrandsire: { name: "Malik" },
        maternalGranddam: { name: "Zahra" },
      },
      achievements: [],
      images: [],
    },
    {
      _id: "zahra",
      name: "Zahra",
      nameAr: "زهرة",
      slug: "zahra",
      breed: "Arabian",
      sex: "mare",
      color: "Bay",
      dateOfBirth: "2020-05-18",
      status: "active",
      isFeatured: true,
      description:
        "Quiet confidence, natural balance, and an unmistakable elegance. A mare with a gentle temperament and a bright future.",
      coverImage: { url: image("zahra") },
      pedigree: {},
      achievements: [],
      images: [],
    },
    {
      _id: "nour",
      name: "Nour",
      nameAr: "نور",
      slug: "nour",
      breed: "Arabian",
      sex: "filly",
      color: "Chestnut",
      dateOfBirth: "2024-03-09",
      status: "active",
      isFeatured: true,
      description:
        "Curious, spirited, and full of promise. Nour is a glimpse of the next generation.",
      coverImage: { url: image("nour") },
      pedigree: {},
      achievements: [],
      images: [],
    },
  ],
  news: [
    {
      _id: "welcome",
      title: "A new chapter for Élevage Benhaimoud",
      titleAr: "فصل جديد لتربية بن حيمود",
      slug: "a-new-chapter",
      excerpt:
        "A place to share our horses, our everyday moments, and the journey ahead.",
      content:
        "Welcome to our digital home. Here, we will share horse profiles, moments from the farm, and news from our breeding journey.\n\nThis is a preview article. Replace it with your own story in the dashboard before launching your website.",
      category: "news",
      isPublished: true,
      publishedAt: "2026-09-01T12:00:00.000Z",
      coverImage: { url: image("landscape") },
    },
    {
      _id: "generation",
      title: "Looking towards the next generation",
      slug: "the-next-generation",
      excerpt:
        "Every new beginning starts with patience, care, and possibility.",
      content:
        "Watching young horses grow is one of the great joys of breeding. Follow their progress here as we add updates and photographs.\n\nThis is sample content for the local preview.",
      category: "birth",
      isPublished: true,
      publishedAt: "2026-08-20T12:00:00.000Z",
      coverImage: { url: image("nour") },
    },
  ],
  gallery: [
    {
      _id: "g1",
      url: image("atlas"),
      type: "photo",
      caption: "The beauty of a quiet moment",
      category: "horses",
      sortOrder: 0,
    },
    {
      _id: "g2",
      url: image("landscape"),
      type: "photo",
      caption: "Space to roam",
      category: "farm",
      sortOrder: 1,
    },
    {
      _id: "g3",
      url: image("zahra"),
      type: "photo",
      caption: "Strength and elegance",
      category: "horses",
      sortOrder: 2,
    },
    {
      _id: "g4",
      url: image("nour"),
      type: "photo",
      caption: "The next chapter",
      category: "foals",
      sortOrder: 3,
    },
  ],
});
